CC=g++
AR=ar
CFLAGS=-I./
SRC=mainapp.cpp nautilusnet.cpp

#rm testm.exe
#rm mainapp.exe	

all: mainapp

mainapp:
    #$(CC) $(SRC) $(CFLAGS) -g -DDEBUG -o mainapp.exe
	$(CC) $(SRC) $(CFLAGS) -g -DDEBUG -o mainapp
	
testm:
    #$(CC) testm.cpp $(CFLAGS) -DDEBUG -o testm.exe
	$(CC) testm.cpp $(CFLAGS) -DDEBUG -o testm
